### ISSUE TITLE
Actions permissions (setup is different from README)

### ISSUE THREAD

**Issue by timholy** [bcbi/CompatHelper.jl#121]
After I enable actions, I get a screen like this:

![image](https://user-images.githubusercontent.com/1525481/68709986-59350b00-055c-11ea-8677-cb97204676b2.png)

Then if I try adding a runner, I get a fairly dire warning:

![image](https://user-images.githubusercontent.com/1525481/68710062-7f5aab00-055c-11ea-8465-71078f427c35.png)

This does not obviously match the description [here](https://github.com/bcbi/CompatHelper.jl#installation).

**Comment by DilumAluthge** [comment]
Hi Tim! It looks like you are setting up CompatHelper on a public repo. Is there any particular reason that you want to set up a self-hosted runner?

My recommendation for a public repo is to use GitHub’s free unlimited compute minutes for public repos, instead of setting up a self-hosted runner.

**Comment by timholy** [comment]
Sounds good. When I click on the Actions tab, what exactly am I supposed to do next? Those screens present me with my choices. There is no "Skip this...", and the 2nd screenshot is the closest thing to an editor window that pops up.

**Comment by DilumAluthge** [comment]
Can you go to https://github.com/timholy/Revise.jl/actions/new and post a screenshot of that?

**Comment by timholy** [comment]
D'oh! There's an Actions tab on the Settings page as well as an Actions tab on the ribbon across the top! (Or whatever you call those UI elements.) Thanks for humoring me!
