### ISSUE TITLE
no method matching _repos_are_the_same(::GitHub.Repo, ::Nothing)

### ISSUE THREAD

**Issue by timholy** [bcbi/CompatHelper.jl#140]
https://github.com/JuliaImages/Images.jl/runs/317468145

**Comment by DilumAluthge** [comment]
Good find. I know the cause. Basically happens when someone made a pull request he repository from a fork, and then the pull request was merged and they deleted the fork.

This should be a pretty easy bag for me to fix.

**Comment by timholy** [comment]
You're a god, @DilumAluthge!
