### ISSUE TITLE
Mention that a custom token is required for running GithHub Actions via CompatHelper.jl?

### ISSUE THREAD

**Issue by tkf** [bcbi/CompatHelper.jl#176]
FYI, I noticed that I had to pass a custom token for GithHub Actions to work in the PRs created by CompatHelper.jl. See this PR https://github.com/tkf/BenchmarkCI.jl/pull/27 before [the commit configuring custom token](https://github.com/tkf/BenchmarkCI.jl/pull/24/commits/87fa8d1a51435cbc3bbd28de693504367981f631) and this one https://github.com/tkf/BenchmarkCI.jl/pull/31 after.  Maybe it is worth noting it in the manual?

I realized this when reading this note in the manual of create-pull-request action: https://github.com/peter-evans/create-pull-request#action-inputs

**Comment by DilumAluthge** [comment]
This is fixed now.

CompatHelper now supports SSH deploy keys. The solution is to use an SSH deploy key. See the CompatHelper README for full details.

We do not recommend that you use a personal access token (PAT). SSH deploy keys are more secure than PATs. For example, a PAT has access to all of your repositories, but an SSH deploy key only has access to a single repository.

**Comment by tkf** [comment]
Thanks a lot for adding the deploy key support. It's good to know that CompatHelper.jl is taking security seriously.
