### ISSUE TITLE
tell users to release after merging

### ISSUE THREAD

**Issue by mkborregaard** [bcbi/CompatHelper.jl#187]
When merging a compathelper PR with passing tests, it would be great if people released new patch versions immediately, as these will often be holding back other packages. Could the auto-text in the PR remind people to please do that? Often people merge the PR but wait long with releasing the compatible version, holding back other packages across the ecosystem.

**Comment by DilumAluthge** [comment]
Absolutely. Want to make a pull request?

**Comment by DilumAluthge** [comment]
It’ll probably go somewhere in here: https://github.com/bcbi/CompatHelper.jl/blob/master/src/new_versions.jl

**Comment by mkborregaard** [comment]
Ha sniped :-p You asked me to open an issue on Slack :-D

**Comment by DilumAluthge** [comment]
That’s how I trick you

**Comment by DilumAluthge** [comment]
I start by asking for an issue

**Comment by DilumAluthge** [comment]
Then I asked for a pull

**Comment by DilumAluthge** [comment]
"If you give a mouse a cookie..."

**Comment by mkborregaard** [comment]
:joy:
