### ISSUE TITLE
Multiple PRs when not using GITHUB_TOKEN

### ISSUE THREAD

**Issue by mileslucas** [bcbi/CompatHelper.jl#188]
Noticed a bug on the `TuringLang/NestedSamplers.jl` repo, which uses my personal access token to allow triggering the CI and auto-testing the compat changes (very useful!). 

What happened was 4 PRs opening for the same compat change, a new one for each CompatHelper CI trigger, which is different than the behavior while using the GITHUB_TOKEN secret. See the PRs here: https://github.com/TuringLang/NestedSamplers.jl/pulls?q=is%3Apr.

**Comment by DilumAluthge** [comment]
This is fixed now.

CompatHelper now supports SSH deploy keys. The solution is to use an SSH deploy key. See the CompatHelper README for full details.

We do not recommend that you use a personal access token (PAT). SSH deploy keys are more secure than PATs. For example, a PAT has access to all of your repositories, but an SSH deploy key only has access to a single repository.
