### ISSUE TITLE
Feature request: SSH private keys that are password-protected

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/CompatHelper.jl#206]
CompatHelper now has support for SSH deploy keys.

Currently, we require that your SSH private key does not have a password.

It would be great if we also had support for SSH private keys that are password-protected.

**Comment by DilumAluthge** [comment]
We need to decide what to call the environment variable that contains the password.

The private key itself goes in the `COMPATHELPER_PRIV` environment variable. (This convention was taken from Franklin.jl, which puts their private keys in the `FRANKLIN_PRIV` environment variable.)

So maybe we can put the password for the private key in an optional environment variable called `COMPATHELPER_PRIV_PASSWORD`.

**Comment by DilumAluthge** [comment]
I believe that Julia TagBot has support for SSH private keys that are password-protected. I wonder how that works.

@christopher-dg

**Comment by christopher-dG** [comment]
It's not too complicated: you start `ssh-agent` and then `ssh-add` the key.
You'll need something like [Expect.jl](https://juliahub.com/ui/Packages/Expect/s6Vti/0.3.1) to enter the password.

https://github.com/JuliaRegistries/TagBot/blob/02eede322f0d1523103c8d45030bfa467bff01e3/tagbot/action/repo.py#L271-L304

**Comment by DilumAluthge** [comment]
Hmmm. Is there a solution that does not require `ssh-agent`?

I'd like to eventually support local use of CompatHelper. Using `ssh-agent` would interfere with the user's regular SSH configuration.

**Comment by christopher-dG** [comment]
You could perhaps write your own SSH wrapper and set it as `core.sshCommand`.

**Comment by DilumAluthge** [comment]
I'm going to close this for now. It looks like it will be complicated to implement without using ssh-agent, which I don't want to use. And I'm not sure how many people would want this feature anyway.
