### ISSUE TITLE
README example out of date?

### ISSUE THREAD

**Issue by ericphanson** [bcbi/CompatHelper.jl#212]
I've been using the example 3
```julia
run: julia -e 'using CompatHelper; CompatHelper.main( (; registries) -> CompatHelper._update_manifests(pwd(); registries = registries) )'
```
so CompatHelper does not update a particular Manifest (which I want to keep for reproducibility), but it's been failing: https://github.com/ericphanson/GuessworkQuantumSideInfo.jl/runs/729164733?check_suite_focus=true. I'm not quite sure how to change it to fix the issue.

**Comment by DilumAluthge** [comment]
Try replacing `pwd()` with `String[pwd()]`.

If that fixes the issue, then we can update the README

**Comment by ericphanson** [comment]
Ok, I'll give it a try!

**Comment by ericphanson** [comment]
Progress! https://github.com/ericphanson/GuessworkQuantumSideInfo.jl/runs/732883246?check_suite_focus=true#step:3:27

**Comment by DilumAluthge** [comment]
Set the `delete_old_manifests` keyword argument to the `_update_manifests` function.

**Comment by ericphanson** [comment]
Would you mind explaining what that does? I don't really get how it could update the manifests but not delete them? Or does it the delete the ones it doesn't update?

I think for me the better solution is actually to just add a github actions CI job to test the project with that manifest separately and then allow CompatHelper to make PRs to update it.

**Comment by ericphanson** [comment]
Ah okay, that makes a lot of sense! I'll send a PR over to update the example and add that info.
