### ISSUE TITLE
CompatHelper doesn't use proxy inside running updates.

### ISSUE THREAD

**Issue by racinmat** [bcbi/CompatHelper.jl#226]
`HTTPS_PROXY` and `HTTP_PROXY` environment variables are not passed. The same goes for `JULIA_PKG_SERVER`.

**Comment by DilumAluthge** [comment]
@racinmat Can you make a PR to fix this issue now?

**Comment by racinmat** [comment]
Done #228

**Comment by DilumAluthge** [comment]
@racinmat Alright, can you make the PR to fix this proxy issue now?

You can bump the patch version number since it will be a bug fix.

**Comment by racinmat** [comment]
Done in #232.
