### ISSUE TITLE
Commiter is $(ci_cfg.username)

### ISSUE THREAD

**Issue by tkf** [bcbi/CompatHelper.jl#229]
Commiter (author?) of the commit created by CompatHelper is `$(ci_cfg.username)`.  For example: https://github.com/tkf/BenchmarkCI.jl/pull/68/commits/ddf755c0bdcce57b666a7a95644a2aae7bdc157c

Maybe some kind of escape problem?

**Comment by DilumAluthge** [comment]
Thanks for the report! I should have this fixed soon.

**Comment by DilumAluthge** [comment]
@tkf I think this is fixed now. The next time CompatHelper opens a PR on one of your repos, can you double-check and make sure that it is fixed for you?

**Comment by tkf** [comment]
Thanks for the quick fix!

I run `CompatHelper#13ec956c066a2a21c1f69a7bb1f9f530ae6e1b7d` (https://github.com/JuliaFolds/Transducers.jl/commit/f4d03c1424eb61b9937e0ceb213c4d3b374b31df / https://github.com/JuliaFolds/Transducers.jl/runs/860125137?check_suite_focus=true) and it created a commit with a proper user name https://github.com/JuliaFolds/Transducers.jl/pull/351/commits/79d144d53ccfdb79ae7be2226f122160001469c4 (https://github.com/JuliaFolds/Transducers.jl/pull/351).
