### ISSUE TITLE
github authentication not respecting passed `env` variable

### ISSUE THREAD

**Issue by racinmat** [bcbi/CompatHelper.jl#231]
https://github.com/bcbi/CompatHelper.jl/blob/master/src/main.jl#L29 and https://github.com/bcbi/CompatHelper.jl/blob/master/src/main.jl#L30 use `env=ENV`, I assume it should be `env=env`, right?

**Comment by DilumAluthge** [comment]
Good catch. They are typos.

You already have a PR open to fix some ENV stuff. Can you also fix these issues in that same PR?

**Comment by racinmat** [comment]
Yes, will do.
