### ISSUE TITLE
No "Actions" tab on repos

### ISSUE THREAD

**Issue by dlfivefifty** [bcbi/CompatHelper.jl#26]
I wanted to install this on my repos, e.g., https://github.com/JuliaArrays/LazyArrays.jl but don't see an action tab

**Comment by fredrikekre** [comment]
GitHub Actions is still in beta for a couple more weeks, you have to explicitly enable it for your user/organization.

**Comment by SaschaMann** [comment]
You can sign up here: https://github.com/features/actions

**Comment by dlfivefifty** [comment]
I signed up for it... but I guess it would need to be enabled for JuliaArrays then?

**Comment by fredrikekre** [comment]
> it would need to be enabled for JuliaArrays then?

Yea, I just did.
