### ISSUE TITLE
Initial PRs to update all compats

### ISSUE THREAD

**Issue by mauro3** [bcbi/CompatHelper.jl#30]
It would be helpful to create PRs when installing this Action to update the compat section to the latest and greatest.  As it is (if I understand correctly), after installing I'll have to wait until a dependency updates until I get a PR.

**Comment by mauro3** [comment]
Scrap that, I was just impatient: https://github.com/mauro3/WhereTheWaterFlows.jl/pull/2

**Comment by DilumAluthge** [comment]
Yeah you just have to wait an hour or so for the first cron job
