### ISSUE TITLE
CompatHelper should keep lower bound

### ISSUE THREAD

**Issue by mauro3** [bcbi/CompatHelper.jl#31]
When updating it should go from
```
[Compat]
Example = "0.1"
```
to
```
[Compat]
Example = "0.1, 0.2"
```
and not as currently
```
[Compat]
Example = "0.2"
```

See https://github.com/mauro3/WhereTheWaterFlows.jl/pull/2#discussion_r342451250 where @fredrikekre pointed this out.

**Comment by mauro3** [comment]
Is there a way to re-run it to "fix" it's PR to my repo?

**Comment by DilumAluthge** [comment]
Close the PR's. The next time the cron job runs, CompatHelper will open new (correct) PR's.
