### ISSUE TITLE
Failed runs of compat helper

### ISSUE THREAD

**Issue by baggepinnen** [bcbi/CompatHelper.jl#36]
I have gotten a few mails with failed runs of compat helper, the log of one such failed event is here
https://github.com/baggepinnen/MonteCarloMeasurements.jl/runs/290182880

**Comment by DilumAluthge** [comment]
Sorry about that! I accidentally broke the master branch. I am currently testing a fix, hope to merge it into master soon.

**Comment by baggepinnen** [comment]
No worries, thanks for your work on this package, will make our jobs a lot easier :D

**Comment by DilumAluthge** [comment]
Once CompatHelper is registered in the General registry (which will happen automatically in less than 3 days), this won't be an issue. But right now since it is unregistered, we are all living on the bleeding edge master.

**Comment by DilumAluthge** [comment]
Thank you for using it! Continue to keep the bug reports coming. It's very helpful to get feedback from people that are using CompatHelper.

**Comment by DilumAluthge** [comment]
I think that this is resolved. Re-open if you get more failures.

**Comment by baggepinnen** [comment]
Some more failed runs
https://github.com/baggepinnen/SingularSpectrumAnalysis.jl/commit/15cdce1eb579ca039362d35850de8f2126be8491/checks

**Comment by DilumAluthge** [comment]
Looks like there was a failure three hours ago due to a transient network failure.

The two most recent builds passed successfully.
