### ISSUE TITLE
Informative commit message

### ISSUE THREAD

**Issue by baggepinnen** [bcbi/CompatHelper.jl#63]
It would be great if the commit message reflected which compat entry was changed, instead of
`Automated commit by CompatHelper.jl` from the branch 
` compathelper/new_version/2019-11-06-06-06-16-381-3275298043`, the commit message would say the same thing as the pull request title.

For instance, when browsing the build log on travis, all I can see is the commit message and the brach name, so it's hard for me to relate to which entry a particular build is testing.

**Comment by DilumAluthge** [comment]
Great idea
