### ISSUE TITLE
Bump version?

### ISSUE THREAD

**Issue by mauro3** [bcbi/CompatHelper.jl#64]
Would it make sense to bump the version as well (but only when it is still at the version in the registry)?

**Comment by DilumAluthge** [comment]
Not a bad idea.

**Comment by DilumAluthge** [comment]
Just FYI - this would only work for packages that are registered. Because we need to look up the latest registered version in the registry (or registries, if you provide a custom list of registries).

Of course, you would still be able to use CompatHelper on unregistered packages. But the "bump my version" feature would not be available. All other features would still be available.

**Comment by DilumAluthge** [comment]
Here's the other question.

We'll have a keyword argument `bump_version::Bool`. So example usage would be:
- `CompatHelper.main(; bump_version = true)`
- `CompatHelper.main(; bump_version = false)`

The question is: what should be the default value of `bump_version`?

**Comment by DilumAluthge** [comment]
I am thinking that the default value should be `bump_version = false`.

If a user wants this "bump version" functionality, it is very easy to use `CompatHelper.main(; bump_version = true)`.

**Comment by DilumAluthge** [comment]
But I could be convinced to make the default value `true` instead, if people feel very strongly about it.

**Comment by fredrikekre** [comment]
How do you know what component to bump though? Major, minor or patch?

**Comment by DilumAluthge** [comment]
It’s a compat change with no other changes - I assume you’d always bump the patch.

**Comment by fredrikekre** [comment]
Yea, but there might have been breaking changes or features on the master branch since the last release.

**Comment by DilumAluthge** [comment]
That’s a good point.

I would have hoped that they would have already bumped the version number in those breaking or feature PR’s.

We’d only bump the version number if it hadn’t yet been bumped after the last registered release.

But you are right, this gets pretty complicated pretty quickly. It might be out of the scope of CompatHelper.
