### ISSUE TITLE
bump compat for "CxxWrap" to "0.8"

### ISSUE THREAD

**Issue by TeroFrondelius** [bcbi/CompatHelper.jl#65]
Here it is https://github.com/JuliaFEM/MFrontInterface.jl/pull/29

The problem relates to `CxxWrap`, because it goes hand in hand with `libcxxwrap`. When I use BinaryBuilder.jl approach the binaries are in the different repo (https://github.com/TeroFrondelius/mgisBuilder), which needs to be released first in order to be able to test new `CxxWrap` version. I hope my explanation makes sense. Anyway, this is the reason why I have fixed the `CxxWrap = "= 0.8.1"`

Maybe CompatHelper shouldn't make a pull request when compat pins exactly one version using "=" sign. What do you think?

**Comment by fredrikekre** [comment]
Thats just a bug, nothing should happen there.

**Comment by fredrikekre** [comment]
Probably caused by https://github.com/bcbi/CompatHelper.jl/pull/33

**Comment by TeroFrondelius** [comment]
Thanks @fredrikekre, I thought so too.

**Comment by DilumAluthge** [comment]
So, technically, this is the intended behavior. CompatHelper wants you to support the latest release of all of your dependencies.

The latest release of `CxxWrap` is `CxxWrap version 0.8.2`.

Your current compat entry is:
```yaml
[compat]
CxxWrap = "= 0.8.1"
```

The compat entry `"= 0.8.1"` does not include the version `0.8.2`. So CompatHelper wants you to broaden your compat entry to include `0.8.2`. There are two possible ways to do this:
1. `CxxWrap = "= 0.8.1, 0.8"`
2. `CxxWrap = "0.8"`

By default, CompatHelper will suggest option 1. (This is the functionality implemented in #33.)

However, if you change your CompatHelper configuration (via keyword arguments to the `CompatHelper.main` function), you can tell CompatHelper to do any of the following:
- Suggest only option 1 (default)
- Suggest only option 2
- Suggest both option 1 and option 2 and let you pick

In my opinion, this is the correct behavior. The purpose of CompatHelper is to make sure that you always support the latest release of a dependency. You currently do not support the latest release of `CxxWrap`, so CompatHelper opened a pull request.

---

So, what do you do if you don't agree with CompatHelper? Easy! Just take the following steps:
1. Apply the `wontfix` label to the pull request, or whatever labels you want. (This step is not required. I just think it's a good idea.)
2. Leave the pull request open. As long as the pull request is open, CompatHelper will see it and will not open another pull request.

In general, if you don't agree with CompatHelper for whatever reason, that's totally fine. It's your repo, and you should make the final decision. Just leave the pull request open and do not merge it. As long as the pull request is open, CompatHelper will not open another pull request that does the same thing.

**Comment by fredrikekre** [comment]
Sorry, I missed the `=`.

**Comment by TeroFrondelius** [comment]
I see it's a feature rather than a bug. I will close this. Thanks for the advice @DilumAluthge.
