### ISSUE TITLE
Cron job will fail with error if one or more dependencies is unregistered

### ISSUE THREAD

**Issue by aminya** [bcbi/CompatHelper.jl#66]
I have added CompatHelper to my package, but it has sent me a lot of emails about it. Where's the problem?
https://github.com/JuliaMusic/MusicXML.jl/runs/291007366

**Comment by DilumAluthge** [comment]
Thanks for the bug report. I'll investigate.

In the meantime, you can turn off email notifications for GitHub Actions: https://help.github.com/en/github/receiving-notifications-about-activity-on-github/choosing-the-delivery-method-for-your-notifications#choosing-the-delivery-method-for-notifications-about-github-actions

**Comment by DilumAluthge** [comment]
I have figured this out.

One of your dependencies (`AcuteML`) is unregistered. This caused an ungraceful error.

If CompatHelper encounters a dependency that is unregistered, we should post a logging message and continue, instead of crashing.

**Comment by DilumAluthge** [comment]
@aminya Thank you again for reporting this!

I think that I have fixed this bug.

If you start getting error messages again, can you re-open this issue?

**Comment by aminya** [comment]
Yes, it is solved. Thank you!
https://github.com/JuliaMusic/MusicXML.jl/commit/36332e21ebf11f4fdc1f14a3f1cdf0f4e87a7f57/checks?check_suite_id=299660075
